Fix AttributeError being raised in buckets controller.
This PS fixes an AttributeError raised in buckets controller
when Deckhand tries to parse a malformed YAML which in turn
causes Deckhand to attempt to raise a 400, but accesses an
invalid attribute in the exception object, causing the
AttributeError.

Example error:

    AttributeError: 'ScannerError' object has no attribute 'format_message'

Change-Id: I54865e4830d3d34e813b1ecfa3105cf6243f2ca0