Update patch set 1
Patch Set 1:

> (1 comment)

> (1 comment)

I had tried that and it works for postgresql but fails for sqlite. Functional tests pass with Unicode, but sqlite fails; tox -e functional passes but tox -e py27 fails. Personally, I think that unit tests should be run with sqlite. Using Unicode would require using postgresql with unit tests.

Error:

oslo_db.exception.DBDataError: (sqlite3.ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

Patch-set: 1